### ISSUE TITLE
Style app summary page

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3376]
Each app has a page that can be viewed by anyone with the link. ChAs use this page to share information about the apps with judges at in-person events. Currently, the page has styling issues that prevent it from being easily used. Pages can be found by:

1. Log in as an admin
2. Click on the submissions tab
3. Click the image icon in the View column
4. Page with URL similar to /apps/no-name-yet-team-1222#/ will load

NOTE: This is best viewed on staging as submissions are still in progress on prod.

## TODO
- [x] Make demo and pitch videos open in a new window
- [x] Update business/adoption plan text
- [x] Label Learning Journey section
- [x] If the Technical Additions section has a Thunkable link, clicking it just reloads the page. This is fixed in [PR304](https://github.com/Iridescent-CM/technovation-app/pull/3404) but listing it here in case something else needs to be changed other than merging that PR.
- [ ] Make pictures clickable to open larger in a pop-up (will be done in #3426)
- [x] Change URL to /projects/

**Comment by dboyer** [comment]
Note that @shaunxp20 requested that he look into this one.

**Comment by dboyer** [comment]
Checked QA and confirmed:
- URL updated to projects
- Videos open in new link
- Business plan/user adoption plan text correct depending on division
- Learning journey section visible and labeled

**Comment by shaunxp20** [comment]
I added a new issue for the #3426.
