### ISSUE TITLE
Add left menu/submission checklist to the submission rebrand layout and remove right side submission information

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4068]
- [ ] Add an energetic container (application/templates/dashboards/side_nav)
- [ ] Add submit button
- [ ] New: Add "Qualifications met" link

- [ ] Remove honor code from right side
- [ ] Remove side submission details and submit project from right side

 ![CleanShot 2023-06-29 at 13.49.50@2x.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/367ab245-c51b-444d-8abc-70426d3a8bed)
![CleanShot 2023-06-29 at 13.51.54@2x.png](https://images.zenhubusercontent.com/606b0f4fd13d53dff3d14fa5/6c59e5d6-7e70-4147-bcd5-e56c953aa37f)
