### ISSUE TITLE
Support Requests - May 16 - June 12

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4739]
- [x] Explore issue with judges being added to an RPE. More [details here](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1715886169191689).
- [x] Restrict LearnWorlds access to only users with a current LearnWorlds account - #4734 and [details here](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1715883827934059)
- [x] Judge shown as both completing and recusing themselves from a score. [Details here](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1715886334154179) and in #4732
- [x] Team not viewable/accessible b/c of "Something went wrong" page. [Details here](https://iridescentlearning.slack.com/archives/C02J1GU8VRA/p1716311923885099)
  - This was due to a join request to the team where the associated student was deleted (potentially b/c they were converted to a mentor) and this was causing an error. To fix this, the join request was deleted. More [details here](https://iridescentlearning.slack.com/archives/C02J1GU8VRA/p1716317254347059)
- [x] Team location was incorrect. [Details here](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1716328528974579)
  - Hard to troubleshoot since team locations are editable; we could add more activity tracking to make this easier to troubleshoot in the future

- [x] Add events column to scores export page #4758

**Comment by dboyer** [comment]
Support request linked to error page when selecting a mentor on a team #4783
