### ISSUE TITLE
Enable students to update chapter or club selection from their profile

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#5154]
Depends on #5153.

On their profile, students and mentors should have an option to change their chapter. This issue covers:

- [ ] Adding an "Update Chapter" or "Update Assignment" button near the chapter displayed on their profile (#5153)
- [ ] If students click to change their chapter, they should see the same chapter selection modal with their current chapter at the top (#5609)
- [ ] Process for updating the chapter will be the same as described in #5609

**Comment by dboyer** [comment]
Update: we should create this as a partial that can be used on the student profile as well as on the screen that students see when they log into a new season and potentially need to update their chapter. A draft wireframe is below.

<img width="338" alt="Image" src="https://github.com/user-attachments/assets/8d606b7b-feb9-405d-89aa-888db3f85128" />

**Comment by dboyer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/gh/Iridescent-CM/technovation-app/5154?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment]
Tested on preview and confirmed:

- I see the button to update my chapter on my profile
- When I click to update, I see a pop-up modal that lists my current chapter. I have the option to update or confirm that chapter.
- I clicked to update and see my chapter listed at the top of the chapter selection modal
- I can click to select another chapter in my country
- I can save the new selection and see the updated chapter in the "meet your ambassador" header and on my profile
- As an admin, I can see the new chapter on the student's admin page
- I logged in as the ChA for the new chapter and I see the student on the list now

I was also able to:
- Change my chapter assignment from a club to a chapter

@shaun-technovation I added #5654 to support letting unaffiliated students choose a chapter from their profile.
